# This file contains config for Home Assistant unique to your installation and should not be overwritten with each update of House Battery Control
# It should be included in the main configuration.yaml file as a `package` via `!include_dir_named` https://www.home-assistant.io/docs/configuration/packages/.
# Use the values below as a `template` for your specific needs

template:
  - sensor:
      # Example: sensor for single-phase power meter
      - name: "L1 Meter Power"
        unique_id: "l1_meter_power"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        state: >
          {% set consumption = states('sensor.electricity_meter_power_consumption_phase_l1') | float(0) %}
          {% set production = states('sensor.electricity_meter_power_production_phase_l1') | float(0) %}
          {{ (consumption - production) | round(2) }}

      # House battery control | Grid power
      # Your P1 meter indicates the power drawn or returned to grid.
      # This "P1 meter power" sensor acts as an alias for you power sensing configuration and is used throughout the node-RED scripts.
      - name: "Grid Power"
        unique_id: "p1_meter_power"
        state: "{{ states('sensor.l1_meter_power') }}" # << SET YOUR GRID POWER SENSOR HERE
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
