# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# System
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Packages
homeassistant:
  packages: !include_dir_named packages

# Enable My for HACS
my:
