# This file is an example for the main Home Assistant configuration.

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder if you have one.
frontend:
  themes: !include_dir_merge_named themes

# Add the following lines if you want to use the example sensors and input/output controls.
# The following lines will include all files from the specified directories.
template: !include_dir_merge_named template_sensors/
input_number: !include_dir_merge_named input_numbers/
input_select: !include_dir_merge_named input_selects/